# Append at the end of /etc/mailman/mm_cfg.py
DEFAULT_ARCHIVE = Off
DEFAULT_REPLY_GOES_TO_LIST = 1
DEFAULT_SUBSCRIBE_POLICY = 3

DEFAULT_MAX_NUM_RECIPIENTS = 30
DEFAULT_MAX_MESSAGE_SIZE = 10000           # KB 
